export const BASE_URL = 'https://localhost:7288'
export const LOGIN_URL_DOCTOR = `${BASE_URL}/doctor`
export const LOGIN_URL_NURSE = `${BASE_URL}/nurse`
export const LOGIN_URL_PATIENT = `${BASE_URL}/patient`
export const ADD_URL_PATIENT = `${BASE_URL}/patientapi/addpatient`
export const ADD_DETAILS_URL_PATIENT = `${BASE_URL}/personalDetails`
export const ADD_ADDRESS_URL_PATIENT = `${BASE_URL}/homeAddress`
export const ADD_VITAL_SIGNS_URL_PATIENT = `${BASE_URL}/vitalSigns`
export const DELETE_PATIENT = `${BASE_URL}/patientapi/deletepatient`
export const GET_PATIENTS = `${BASE_URL}/patientapi/getall`
export const GET_DOCTORS_BYNAME = `${BASE_URL}/patientapi/getbydoctorname`
export const GET_PATIENTS_BYNAME= `${BASE_URL}/patientapi/getbypatientname`
export const GET_LABORATORY_ANALYSIS = `${BASE_URL}/getall`
export const ADD_ANALYSIS_RESULT = `${BASE_URL}/insertResults`
export const CHANGE_PASSWORD = `${BASE_URL}/nurseapi`